// examples/preact/src/sidebar/SidebarApp.tsx
import './styles.css'
import logo from '../images/icon.png'

export default function SidebarApp() {
  return (
    <div className="sidebar_app">
      <img className="sidebar_logo" src={logo} alt="The Preact logo" />
      <h1 className="sidebar_title">Sidebar Panel</h1>
      <p className="sidebar_description">
        Learn more in the{' '}
        <a
          href="https://extension.js.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Extension.js docs
        </a>.
      </p>
    </div>
  )
}

// examples/svelte/src/sidebar/SidebarApp.svelte
<script lang="ts">
import logo from '../images/icon.png'
</script>

<div class="sidebar_app">
  <img class="sidebar_logo" src={logo} alt="The Svelte logo" />
  <h1 class="sidebar_title">Sidebar Panel</h1>
  <p class="sidebar_description">
    Learn more in the
    <a
      href="https://extension.js.org"
      target="_blank"
      rel="noopener noreferrer"
    >Extension.js docs</a>.
  </p>
</div>
