// examples/content-react/src/content/ContentApp.tsx
import React from 'react'
import reactLogo from '../images/react.png'
import tailwindBg from '../images/tailwind_bg.png'
import typescriptLogo from '../images/typescript.png'
import tailwindLogo from '../images/tailwind.png'
import chromeWindowBg from '../images/chromeWindow.png'

export default function ContentApp() {
  const [isdialogOpen, setIsDialogOpen] = React.useState(true)

  if (!isdialogOpen) {
    return (
      <div className="mx-auto p-6">
        <button
          onClick={() => setIsDialogOpen(true)}
          className="bg-white rounded-md p-3 text-sm font-semibold text-gray-900 shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
        >
          Open content script hint <span aria-hidden="true">+</span>
        </button>
      </div>
    )
  }

  return (
    <div className="mx-auto max-w-7xl md:px-0 lg:p-6">
      <div className="relative isolate overflow-hidden bg-gray-900 px-6 pt-16 shadow-2xl lg:rounded-3xl md:pt-24 md:h-full sm:h-[100vh] lg:flex lg:flex-wrap lg:gap-x-20 lg:px-24 lg:pt-0">
        <div className="absolute z-20 top-0 inset-x-0 flex justify-center overflow-hidden pointer-events-none">
          <div className="w-[108rem] flex-none flex justify-end">
            <picture>
              <img
                src={tailwindBg}
                alt=""
                className="w-[90rem] flex-none max-w-none hidden dark:block"
                decoding="async"
              />
            </picture>
          </div>
        </div>
        <div className="mx-auto max-w-md text-center lg:py-12 lg:mx-0 lg:flex-auto lg:text-left">
          <div className="flex items-center justify-center space-x-4 my-4 mx-auto">
            <img
              alt="React logo"
              src={reactLogo}
              className="relative inline-block w-12"
            />
            <div className="text-3xl text-white">+</div>
            <img
              alt="TypeScript logo"
              src={typescriptLogo}
              className="relative inline-block w-12"
            />
            <div className="text-3xl text-white">+</div>
            <img
              alt="Tailwind logo"
              src={tailwindLogo}
              className="relative inline-block w-12"
            />
          </div>
          <h2 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
            This is a content script running React, TypeScript, and Tailwind.css
          </h2>
          <p className="mt-6 text-lg leading-8 text-gray-300">
            Learn more about creating cross-browser extensions by{' '}
            <button
              onClick={() => setIsDialogOpen(false)}
              className="underline hover:no-underline
            "
            >
              closing this hint
            </button>
            .
          </p>
        </div>
        <div className="relative mt-16 h-80 lg:mt-8">
          <img
            className="absolute left-0 top-0 w-[57rem] max-w-none rounded-md bg-white/5 ring-1 ring-white/10"
            src={chromeWindowBg}
            alt="Chrome window screenshot"
            width="1824"
            height="1080"
          />
        </div>
        {/* Last child of the card, full width so it wraps below both columns
            rather than becoming a third one. Every other content template ends
            on this button, and the framework ones used to bury it beside the
            screenshot. */}
        <div className="w-full pb-12 text-center lg:pb-16">
          <button
            onClick={() => chrome.runtime.sendMessage({type: 'open-options'})}
            aria-label="Open options"
            className="rounded-md bg-white px-3.5 py-2.5 text-sm font-semibold text-gray-900 shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
          >
            Open options
          </button>
        </div>
      </div>
    </div>
  )
}

// public/content-vue/src/content/ContentApp.vue
<script lang="ts" setup>
import {ref} from 'vue'

const isdialogOpen = ref(true)

// A content script cannot open the options page, so the background script
// relays the click for us.
function openOptions() {
  chrome.runtime.sendMessage({type: 'open-options'})
}
</script>
<template>
  <div v-if="isdialogOpen">
    <div class="mx-auto max-w-7xl md:px-0 lg:p-6">
      <div
        class="relative isolate overflow-hidden bg-gray-900 px-6 pt-16 shadow-2xl lg:rounded-3xl md:pt-24 md:h-full sm:h-[100vh] lg:flex lg:flex-wrap lg:gap-x-20 lg:px-24 lg:pt-0"
      >
        <div
          class="absolute z-20 top-0 inset-x-0 flex justify-center overflow-hidden pointer-events-none"
        >
          <div class="w-[108rem] flex-none flex justify-end">
            <picture>
              <img
                src="../images/tailwind_bg.png"
                alt=""
                class="w-[90rem] flex-none max-w-none hidden dark:block"
                decoding="async"
              />
            </picture>
          </div>
        </div>

        <div
          class="mx-auto max-w-md text-center lg:py-12 lg:mx-0 lg:flex-auto lg:text-left"
        >
          <div
            class="flex items-center justify-center space-x-4 my-4 mx-auto"
          >
            <img
              alt="Vue logo"
              src="../images/logo.svg"
              class="relative inline-block w-12"
            />
            <div class="text-3xl text-white">+</div>
            <img
              alt="TypeScript logo"
              src="../images/typescript.png"
              class="relative inline-block w-12"
            />
            <div class="text-3xl text-white">+</div>
            <img
              alt="Tailwind logo"
              src="../images/tailwind.png"
              class="relative inline-block w-12"
            />
          </div>
          <h2
            class="text-3xl font-bold tracking-tight text-white sm:text-4xl"
          >
            This is a content script running Vue, TypeScript, and Tailwind.css.
          </h2>
          <p class="mt-6 text-lg leading-8 text-gray-300">
            Learn more about creating cross-browser extensions by
            <button
              @click="isdialogOpen = false"
              class="underline hover:no-underline
            "
            >
              closing this hint
            </button>
            .
          </p>
        </div>

        <div class="relative mt-16 h-80 lg:mt-8">
          <img
            class="absolute left-0 top-0 w-[57rem] max-w-none rounded-md bg-white/5 ring-1 ring-white/10"
            src="../images/chromeWindow.png"
            alt="Chrome window screenshot"
            width="1824"
            height="1080"
          />
        </div>

        <!-- Last child of the card, full width so it wraps below both columns
             rather than becoming a third one. Every other content template ends
             on this button, and the framework ones used to bury it beside the
             screenshot. -->
        <div class="w-full pb-12 text-center lg:pb-16">
          <button
            @click="openOptions"
            aria-label="Open options"
            class="bg-white rounded-md px-4 py-2 text-sm font-semibold text-gray-900 shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
          >
            Open options
          </button>
        </div>
      </div>
    </div>
  </div>

  <div v-else>
    <div class="mx-auto p-6">
      <button
        @click="isdialogOpen = true"
        class="bg-white rounded-md p-3 text-sm font-semibold text-gray-900 shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
      >
        Open content script hint <span aria-hidden="true">+</span>
      </button>
    </div>
  </div>
</template>
