// examples/vue/src/content/ContentApp.vue
<script>
import vueLogo from '../images/icon.png'
import {defineComponent} from 'vue'

// Named one by one so the bundler can fold each build down to a single
// branch. waterfox and librewolf are gecko, and used to fall to chromium.
const isFirefoxLike =
  import.meta.env.EXTENSION_PUBLIC_BROWSER === 'firefox' ||
  import.meta.env.EXTENSION_PUBLIC_BROWSER === 'waterfox' ||
  import.meta.env.EXTENSION_PUBLIC_BROWSER === 'librewolf' ||
  import.meta.env.EXTENSION_PUBLIC_BROWSER === 'gecko-based'

export default defineComponent({
  name: 'ContentApp',
  setup() {
    const openSidebar = () => {
      chrome.runtime.sendMessage({type: 'openSidebar'})
    }

    return {vueLogo, openSidebar, isFirefoxLike}
  }
})
</script>

<template>
  <!-- Firefox cannot open a sidebar from a message listener, so the gecko build
       renders a hint naming the toolbar action instead of a dead control. -->
  <div v-if="isFirefoxLike" class="content_pill content_pill_static">
    <img class="content_pill_logo" :src="vueLogo" alt="" aria-hidden="true" />
    <span class="content_pill_text"
      >Use the toolbar icon to open the sidebar</span
    >
  </div>
  <button
    v-else
    type="button"
    class="content_pill"
    aria-label="Open sidebar"
    @click="openSidebar"
  >
    <img class="content_pill_logo" :src="vueLogo" alt="" aria-hidden="true" />
    <span class="content_pill_text">Open sidebar</span>
  </button>
</template>

// examples/svelte/src/content/ContentApp.svelte
<script>
import logo from '../images/icon.png'

// Named one by one so the bundler can fold each build down to a single
// branch. waterfox and librewolf are gecko, and used to fall to chromium.
const isFirefoxLike =
  import.meta.env.EXTENSION_PUBLIC_BROWSER === 'firefox' ||
  import.meta.env.EXTENSION_PUBLIC_BROWSER === 'waterfox' ||
  import.meta.env.EXTENSION_PUBLIC_BROWSER === 'librewolf' ||
  import.meta.env.EXTENSION_PUBLIC_BROWSER === 'gecko-based'

function openSidebar() {
  chrome.runtime.sendMessage({type: 'openSidebar'})
}
</script>

<!-- Firefox cannot open a sidebar from a message listener, so the gecko build
     renders a hint naming the toolbar action instead of a dead control. -->
{#if isFirefoxLike}
  <div class="content_pill content_pill_static">
    <img class="content_pill_logo" src={logo} alt="" aria-hidden="true" />
    <span class="content_pill_text">Use the toolbar icon to open the sidebar</span>
  </div>
{:else}
  <button
    type="button"
    class="content_pill"
    aria-label="Open sidebar"
    on:click={openSidebar}
  >
    <img class="content_pill_logo" src={logo} alt="" aria-hidden="true" />
    <span class="content_pill_text">Open sidebar</span>
  </button>
{/if}
